// <auto-generated />
namespace AyuboGUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removed_dates_from_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_dates_from_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202207111253448_removed_dates_from_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
